---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig

- name: Manager
  hosts: managers
  roles:
    - role: preconfig

- name: Worker
  hosts: workers
  roles:
    - role: preconfig
