galaxy_info:
  role_name: swarm_join
  description: Присоединение к кластеру swarm
  author: Artem Khamitov
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
